vpc_cidr_block                  = "10.10.0.0/16"
environment                     = "test"
product                         = "capstone"
public_app_subnet_cidr_a        = "10.10.0.0/24"
public_app_subnet_cidr_b        = "10.10.1.0/24"
private_db_subnet_cidr_a        = "10.10.10.0/24"
private_db_subnet_cidr_b        = "10.10.11.0/24"
private_db_subnet_cidr_c        = "10.10.12.0/24"
mysql_port                      = "4477"
rds_subnetgroupname             = "caps-subnetgroup"
rds_paramgroupname              = "caps-mysql57-params"
rds_storage_size                = "10"
rds_storage_type                = "gp2"
rds_engine                      = "mysql"
rds_engine_version              = "5.7"
rds_instance_size               = "db.t2.micro"
rds_name                        = "caps-db"

